### ISSUE TITLE
Quality/Latency tradeoff control? AKA Variable frame size

### ISSUE THREAD

**Issue by unfa** [lucianodato/libspecbleach#16]
AFAIK noise-repellent has a fixed latency.

I wonder if there could be a way to control the amount of delay somehow.

In some cases one could sacrifice some quality to get faster operation for semi-live usage like video live streaming or VoIP.

I have no idea if this is possible, so let me know.

**Comment by lucianodato** [comment]
@unfa the new version has a separate plugin with lower latency. It makes sense because it doesn't need too much resolution for voice signals. Would this fulfill what you wanted here? Having it variable would be adding a lot of code for a feature that is not going to be that much used. Let me know what you think

**Comment by unfa** [comment]
Sure, that seems sufficient!
